[package]
name = "time_tracker_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
gloo = "0.7"
wasm-bindgen = "0.2.81"
stylist = { version = "0.10.1", features = ["yew"] }
